baseurl = "https://master.dnfrtzpe47ih5.amplifyapp.com/"
languageCode = "en-us"
title = "Tech U Cohort 5"
theme = "my-hugo-cards"
#themesDir = "../.."
paginate = 6

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"

